---
name: "JellyfinHeaderAuth"
guid: "aa50c76e-63c6-4479-97e4-18299a29a3bb"
version: "2"
targetAbi: "10.8.0.0"
framework: "net8.0"
overview: "Jellyfin plugin for header based authentication"
description: >
  This plugin authenticates users based on the 'X-Forwarded-UserName' header value. Forked from pikami.

category: "Authentication"
owner: "calebjonasson"
artifacts:
  - "Jellyfin.Plugin.JellyfinHeaderAuth.dll"
changelog: >
  changelog

